# 轴向GATr模型配置，用于OMAD-6图像分割
# 更适合处理2D图像的空间结构

# 模型类型
_target_: gatr.experiments.omad6.wrappers.OMAD6AxialGATrWrapper

# 网络参数
net:
  _target_: gatr.nets.axial_gatr.AxialGATr
  
  # 输入输出通道
  in_mv_channels: ${data.mv_channels_in}      # 4: 坐标点 + R + G + B  
  out_mv_channels: ${data.mv_channels_out}    # 1: 分割特征
  hidden_mv_channels: 16                      # 隐藏多重向量通道数（轴向版本可以更小）
  
  in_s_channels: ${data.scalar_channels_in}   # 1: dummy标量输入
  out_s_channels: ${data.scalar_channels_out} # 1: 标量输出用于分类
  hidden_s_channels: 8                        # 隐藏标量通道数
  
  # 网络结构
  num_blocks: 6  # 轴向transformer块数量
  
  # 注意力配置
  attention:
    _target_: gatr.layers.attention.config.SelfAttentionConfig
    num_heads: 2  # 较少的注意力头数
    key_query_embed_dim: 64
    value_embed_dim: 64  
    hidden_dim: 128
    pos_encodings: false
    output_init: small
    
  # MLP配置
  mlp:
    _target_: gatr.layers.mlp.config.MLPConfig
    hidden_dim: 64
    num_layers: 2
    output_init: small
    
  # 轴向GATr特定参数
  pos_encodings: [false, false]  # [行位置编码, 列位置编码]
  collapse_dims: [false, false]  # [是否在偶数块折叠维度, 是否在奇数块折叠维度]
  
  # 正则化
  dropout_prob: 0.1
  
  # 性能优化
  checkpoint: null

# 分割特定参数
num_classes: ${data.num_classes}  # 分割类别数量
image_size: ${data.image_size}    # 图像尺寸，用于2D网格重塑