# 内存优化的轴向GATr模型配置，用于OMAD-6图像分割
_target_: gatr.experiments.omad6.wrappers.OMAD6AxialGATrWrapper

# 网络参数 - 内存优化版本
net:
  _target_: gatr.nets.axial_gatr.AxialGATr
  
  # 输入输出通道
  in_mv_channels: ${data.mv_channels_in}      # 4: 坐标点 + R + G + B  
  out_mv_channels: ${data.mv_channels_out}    # 1: 分割特征
  hidden_mv_channels: 4                       # 进一步减少隐藏多重向量通道数
  
  in_s_channels: ${data.scalar_channels_in}   # 1: dummy标量输入
  out_s_channels: ${data.scalar_channels_out} # 1: 标量输出用于分类
  hidden_s_channels: 2                        # 进一步减少隐藏标量通道数
  
  # 网络结构 - 最小化复杂度
  num_blocks: 2                               # 最小化轴向transformer块数量
  dropout_prob: 0.1                           # 正则化
  checkpoint: true                            # 启用checkpoint以节省内存
  
  # 轴向GATr特定参数
  pos_encodings: [false, false]               # [行位置编码, 列位置编码]
  collapse_dims: [false, false]               # [折叠维度选项]

# 分割特定参数
num_classes: ${data.num_classes}              # 分割类别数量
image_size: ${data.image_size}                # 图像尺寸，用于2D网格重塑

# 使用默认的注意力和MLP配置
defaults:
  - /base_attention@net.attention
  - /base_mlp@net.mlp 