# GATr模型配置，用于OMAD-6图像分割
_target_: gatr.experiments.omad6.wrappers.OMAD6GATrWrapper

# 网络参数
net:
  _target_: gatr.nets.gatr.GATr
  
  # 输入输出通道
  in_mv_channels: ${data.mv_channels_in}      # 3: R + G + B（RGB-only 输入）
  out_mv_channels: ${data.mv_channels_out}    # 1: 分割特征
  hidden_mv_channels: 32                      # 隐藏多重向量通道数
  
  in_s_channels: ${data.scalar_channels_in}   # 1: dummy标量输入
  out_s_channels: ${data.scalar_channels_out} # 1: 标量输出用于分类
  hidden_s_channels: 16                       # 隐藏标量通道数
  
  # 网络结构
  num_blocks: 8                               # transformer块数量
  dropout_prob: 0.1                           # 正则化
  checkpoint: null                            # 梯度检查点

# 分割特定参数
num_classes: ${data.num_classes}              # 分割类别数量

# 使用默认的注意力和MLP配置
defaults:
  - /base_attention@net.attention
  - /base_mlp@net.mlp