exp_name: omad6
run_name: ???

base_dir: ???
exp_dir: '${base_dir}/experiments/${exp_name}/${run_name}'

seed: ???
debug: false

checkpoint: null

data:
  data_dir: '${base_dir}/data/OMAD-6'  # OMAD-6数据集路径
  subsample: null  # 子采样率，用于快速实验
  
  # 数据参数 - 效果优化
  image_size: 160  # 平衡效果和内存：128->160
  max_items: 25600  # 160*160 = 25600，完整图像像素
  num_classes: 7   # 分割类别数量：背景(0) + 6个海岸养殖地物类别(TCC, DWCC, FRC, LC, RC, BC)
  
  # 网络输入输出通道
  mv_channels_in: 4    # 多重向量输入通道：坐标点 + R + G + B
  mv_channels_out: 1   # 多重向量输出通道：分割特征
  scalar_channels_in: 1   # 标量输入通道
  scalar_channels_out: 1  # 标量输出通道

training:
  # 训练参数 - 优化以提升全类别学习
  steps: 15000  # 适中的训练步数
  batchsize: 2   # 平衡内存和训练稳定性
  eval_batchsize: 1
  
  # 优化器参数 - 效果优化
  lr: 2e-3       # 稍微提高学习率，加快收敛
  lr_decay: 0.8  # 更温和的学习率衰减
  clip_grad_norm: 1.0    # 放宽梯度裁剪
  weight_decay: 1e-4     # 增加正则化
  
  # 训练策略
  early_stopping: true
  use_focal_loss: true   # 使用Focal Loss处理数据不平衡
  
  # 精度和优化
  float16: true   # 启用混合精度训练节省内存
  ema: true       # 启用EMA提升模型稳定性
  ema_decay: 0.999
  
  # 日志和验证频率
  log_every_n_steps: 50
  validate_every_n_steps: 500
  plot_every_n_steps: 1000
  save_model_every_n_steps: 1000
  update_lr_every_n_steps: 500
  
  # 设备和调试
  eval_device: cuda
  progressbar: true
  detect_anomaly: false
  num_workers: 2
  
  # 注意力优化
  force_xformers: false
  enable_flash_sdp: false
  enable_math_sdp: true
  enable_mem_efficient_sdp: false

# MLflow跟踪
mlflow:
  db: '${base_dir}/tracking/mlflow.db'
  artifacts: '${base_dir}/tracking/artifacts'

defaults:
  - model: gatr_omad6  # 默认使用GATr模型
  - hydra
  - _self_