exp_name: omad6
run_name: ???

base_dir: ???
exp_dir: '${base_dir}/experiments/${exp_name}/${run_name}'

seed: ???
debug: false

checkpoint: null

data:
  data_dir: '${base_dir}/data/OMAD-6'  # OMAD-6数据集路径
  subsample: null  # 子采样率，用于快速实验
  
  # 数据参数
  image_size: 256  # 图像尺寸
  max_items: 1024  # 每张图像最大像素数量
  num_classes: 7   # 分割类别数量：背景(0) + 6个海岸养殖地物类别(TCC, DWCC, FRC, LC, RC, BC)
  
  # 网络输入输出通道
  mv_channels_in: 4    # 多重向量输入通道：坐标点 + R + G + B
  mv_channels_out: 1   # 多重向量输出通道：分割特征
  scalar_channels_in: 1   # 标量输入通道
  scalar_channels_out: 1  # 标量输出通道

training:
  # 训练参数 - 优化以提升全类别学习
  steps: 20000  # 训练步数
  batchsize: 4  # 批次大小
  eval_batchsize: 2
  
  # 优化器参数 - 基于训练结果优化
  lr: 1e-3  # 学习率
  lr_decay: 0.5  # 学习率衰减
  clip_grad_norm: 0.5  # 梯度裁剪
  weight_decay: 5e-5  # 权重衰减
  
  # 训练策略
  early_stopping: true
  use_focal_loss: true   # 使用Focal Loss处理数据不平衡
  
  # 精度和优化
  float16: false  # 混合精度训练
  ema: false
  
  # 日志和验证频率
  log_every_n_steps: 50
  validate_every_n_steps: 500
  plot_every_n_steps: 1000
  save_model_every_n_steps: 1000
  update_lr_every_n_steps: 500
  
  # 设备和调试
  eval_device: cuda
  progressbar: true
  detect_anomaly: false
  num_workers: 2
  
  # 注意力优化
  force_xformers: false
  enable_flash_sdp: false
  enable_math_sdp: true
  enable_mem_efficient_sdp: false

# MLflow跟踪
mlflow:
  db: '${base_dir}/tracking/mlflow.db'
  artifacts: '${base_dir}/tracking/artifacts'

defaults:
  - model: gatr_omad6  # 默认使用GATr模型
  - hydra
  - _self_